version: '3.9'

services:
  backend:
    platform: linux/amd64
    image: wtkeqrf0/while.act:main
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    platform: linux/amd64
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: "while.act"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5




