version: '3.9'

services:
  backend:
    container_name: backend
    platform: linux/amd64
    image: wtkeqrf0/while-act-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: postgres
    platform: linux/amd64
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: "while.act"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 6s
      timeout: 5s
      retries: 10

  redis:
    container_name: redis
    platform: linux/amd64
    image: redis:7.0.9-alpine3.17
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 8s
      timeout: 5s
      retries: 5
